drop table if exists to_stat_flow_info;
create table to_stat_flow_info(
  flow_id bigint,
  rec_id int,
  task_num varchar(20),
  create_time datetime,
  event_desc varchar(2000),
  address varchar(2000),
  act_property_id int,
  display_style_id int,
  coordinate_x double,
  coordinate_y double,
  event_src_id int,
  event_src_name varchar(255),
  event_type_id int,
  event_type_name varchar(100),
  main_type_id int,
  main_type_name varchar(100),
  sub_type_id int,
  sub_type_name varchar(100),
  district_id int,
  district_name varchar(40),
  street_id int,
  street_name varchar(40),
  community_id int,
  community_name varchar(40),
  act_id int,
  cur_stage_id tinyint(1),
  cur_stage_name varchar(10),
  flow_used float,
  flow_num tinyint default 1,
  rs_check_used float,
  check_used float,
  overtime_flag tinyint default 0,
  start_time datetime,
  end_time datetime,
  deadline_time datetime,
  stat_flag tinyint(1) default 1,
  primary key (flow_id, create_time)
) partition by range columns (create_time)(
    partition crt_201703 values less than ('2017-04-01 00:00:00'),
    partition crt_more values less than (maxvalue)
);
create index idx_stat_flow_info_01 on to_stat_flow_info(rec_id);